### ISSUE TITLE
under Windows (8 at least) SNAPSHOT dependencies can't be resolved

### ISSUE THREAD

**Issue by bergm** [tailrecursion/boot#10]
I guess this is specific to Windows and I hope not just my machine. But when I use 'boot' SNAPSHOT dependencies can't be resolved. E.g. starting hoplife with 'boot dev' shows the following error output:

$ boot dev
Error: Could not find artifact tailrecursion:boot.notify:jar:2.0.0-SNAPSHOT in http://repo1.maven.org/maven2/ (http://repo1.maven.org/maven2/)
Error: Could not find artifact tailrecursion:boot.ring:jar:0.1.0-SNAPSHOT in http://repo1.maven.org/maven2/ (http://repo1.maven.org/maven2/)
Error: Could not find artifact tailrecursion:boot.notify:jar:2.0.0-SNAPSHOT in http://clojars.org/repo/ (http://clojars.org/repo/)
Error: Could not find artifact tailrecursion:boot.ring:jar:0.1.0-SNAPSHOT in http://clojars.org/repo/ (http://clojars.org/repo/)
The following artifacts could not be resolved: tailrecursion:boot.notify:jar:2.0.0-SNAPSHOT, tailrecursion:boot.ring:jar:0.1.0-SNAPSHOT: Could not find artifact tailrecursion:boot.notify:jar:2.0.0-SNAPSHOT in http://repo1.maven.org/maven2/ (http://repo1.maven.org/maven2/)
? Caused by: The following artifacts could not be resolved: tailrecursion:boot.notify:jar:2.0.0-SNAPSHOT, tailrecursion:boot.ring:jar:0.1.0-SNAPSHOT: Could not find artifact tailrecursion:boot.notify:jar:2.0.0-SNAPSHOT in http://repo1.maven.org/maven2/ (http://repo1.maven.org/maven2/)
? Caused by: Could not find artifact tailrecursion:boot.notify:jar:2.0.0-SNAPSHOT in http://repo1.maven.org/maven2/ (http://repo1.maven.org/maven2/)

This is true for cygwin and also normal commandline use (directly via boot.jar).
I'm so far quite convinced that it's the SNAPSHOT suffix, as for instance adding 

[lein-pprint "1.1.1"]

or 

[lein-pprint "1.1.2-SNAPSHOT"]

to the deps file cause the dependency resolution to succeed or fail. This is true for other examples as well, if there are SNAPSHOT and regular releases on clojars.

I tried to check the boot and pomegranate code, but at least couldn't quickly find the place where things go wrong. Maybe one of you guys can help faster.

**Comment by micha** [comment]
That's weird. I don't have a windows 8 VM handy to debug this, though.

**Comment by bergm** [comment]
I'll try to find it, if I find the time. Luckily there aren't that many SNAPSHOT versions and boot.notify/ring can easily be referenced by source if needed. :)

**Comment by bergm** [comment]
I found where the problem lies and have a workaround. 
Making the SNAPSHOT lowercase (-> [tailrecursion/boot.notify "2.0.0-snapshot"]) allows aether to resolve the dependency. Don't know what can be done about it. I traced it back to 'resolve-dependencies\* in 'cemerick.pomegranate.aether, but there things disappear in line '(.resolveDependencies system session (DependencyRequest. collect-request nil)) which is code from Javaland and I stopped here as getting this debugged is getting more difficult. 
I don't know what to make of this and whether to close this issue.

At least there's a way to make it work for now. Does anybody else on a Windows system experience this? Can't imagine I'm the only one so far who tried to run some of the Hoplon-Demos on Windows. For me this happens under Cygwin and normal DOS prompt. ....

**Comment by danielneal** [comment]
Yep, I'm seeing this on Windows 7 too...unfortunately I can't get the lower-case workaround to work either.

**Comment by mynomoto** [comment]
Windows users can try with the updated libs that micha released today (non snapshot versions). The hoplon-demos repo is already updated as is the hoplon-castra template. But the issue with snapshot libs is not yet solved.

**Comment by micha** [comment]
There are also binaries available now for Windows users who are having trouble building the Jar file: https://github.com/tailrecursion/boot#windows
