### ISSUE TITLE
boot doesn't pass additional authenticated repositories through to pomegrante

### ISSUE THREAD

**Issue by bergm** [tailrecursion/boot#11]
In order to use the castra dev ring server with Datomic pro easily, boot needs to allow authenticated third party repositories. 
In leiningen this config entry adds the Datomic repository:

:repositories #{{:url "https://my.datomic.com/repo"
                      :username "username.email@address.com"
                      :password "datomic-password"}}

If I find the time I'll add it myself and send a pull request, but maybe for you guys this is just a matter of minutes. :) ?

If I remember correctly, right now repositories must be a string, but a map for the above case should be allowed.

**Comment by micha** [comment]
I'm working on this now. It'll be in the `dev` branch.

**Comment by micha** [comment]
Implemented in boot2 [boot-clj/boot](http://github.com/boot-clj/boot).
