### ISSUE TITLE
Support private S3 repositories

### ISSUE THREAD

**Issue by micha** [tailrecursion/boot#12]
See https://github.com/technomancy/s3-wagon-private

**Comment by jumblerg** [comment]
another battery that merits inclusion, imho, with boot 2 since datomic has made this a common use case.  sample peer installation instructions for leiningen follow:

``` clojure
;; ~/.lein/credentials.clj.gpg (see the Leiningen deploy authentication docs)
{#"my\.datomic\.com" {:username "jumblerg@mail.com" :password "4f4b86a0-3654-11e4-8c21-0800200c9a66"}}

;; project.clj
:repositories {"my.datomic.com" {:url "https://my.datomic.com/repo" :creds :gpg}}
```

also reference https://github.com/technomancy/leiningen/blob/master/doc/DEPLOY.md#authentication.

**Comment by micha** [comment]
This is implemented in boot2 [boot-clj/boot](https://github.com/boot-clj/boot).
