### ISSUE TITLE
boot 1.0.3 throws FileNotFoundException (at least Windows 8)

### ISSUE THREAD

**Issue by bergm** [tailrecursion/boot#13]
Hi,

just tried 1.0.3 to see if issue #10 disappeared. I hope this is not again some Windows issue which is harder to test for you, but for some reason a 'boot dev' for instance in hoplife throws an FileNotFoundException for pomegranate_init:

java.io.FileNotFoundException: Could not locate cemerick/pomegranate__init.class or cemerick/pomegranate.clj on classpath:
 at clojure.lang.RT.load (RT.java:443)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5018.invoke (core.clj:5530)
    clojure.core$load.doInvoke (core.clj:5529)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5336)
    clojure.core$load_lib$fn__4967.invoke (core.clj:5375)
    clojure.core$load_lib.doInvoke (core.clj:5374)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:619)
    clojure.core$load_libs.doInvoke (core.clj:5413)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:619)
    clojure.core$require.doInvoke (core.clj:5496)
    clojure.lang.RestFn.invoke (RestFn.java:619)
    tailrecursion.boot.core$eval40$loading__4910__auto____41.invoke (core.clj:10)
    tailrecursion.boot.core$eval40.invoke (core.clj:10)
    clojure.lang.Compiler.eval (Compiler.java:6619)
    clojure.lang.Compiler.eval (Compiler.java:6608)
    clojure.lang.Compiler.load (Compiler.java:7064)
    clojure.lang.RT.loadResourceScript (RT.java:370)
    clojure.lang.RT.loadResourceScript (RT.java:361)
    clojure.lang.RT.load (RT.java:440)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5018.invoke (core.clj:5530)
    clojure.core$load.doInvoke (core.clj:5529)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5336)
    clojure.core$load_lib$fn__4967.invoke (core.clj:5375)
    clojure.core$load_lib.doInvoke (core.clj:5374)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:619)
    clojure.core$load_libs.doInvoke (core.clj:5413)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:619)
    clojure.core$require.doInvoke (core.clj:5496)
    clojure.lang.RestFn.invoke (RestFn.java:930)
    tailrecursion.boot$eval3$loading__4910__auto____4.invoke (boot.clj:9)
    tailrecursion.boot$eval3.invoke (boot.clj:9)
    clojure.lang.Compiler.eval (Compiler.java:6619)
    clojure.lang.Compiler.eval (Compiler.java:6608)
    clojure.lang.Compiler.load (Compiler.java:7064)
    clojure.lang.RT.loadResourceScript (RT.java:370)
    clojure.lang.RT.loadResourceScript (RT.java:361)
    clojure.lang.RT.load (RT.java:440)
    clojure.lang.RT.load (RT.java:411)
    clojure.core$load$fn__5018.invoke (core.clj:5530)
    clojure.core$load.doInvoke (core.clj:5529)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    clojure.core$load_one.invoke (core.clj:5336)
    clojure.core$load_lib$fn__4967.invoke (core.clj:5375)
    clojure.core$load_lib.doInvoke (core.clj:5374)
    clojure.lang.RestFn.applyTo (RestFn.java:142)
    clojure.core$apply.invoke (core.clj:619)
    clojure.core$load_libs.doInvoke (core.clj:5413)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invoke (core.clj:619)
    clojure.core$require.doInvoke (core.clj:5496)
    clojure.lang.RestFn.invoke (RestFn.java:408)
    tailrecursion.boot.loader$_main.doInvoke (loader.clj:186)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    tailrecursion.boot.loader.main (:-1)

pomegranate 0.2.0 is in .m2, so maybe something during the classloader magic is not working properly. I thought that something from the classloader uberjar might be missing in the uberjar build for boot itself. Adding 

[com.cemerick/pomegranate "0.2.0" :exclusions [org.clojure/clojure]]
[digest "1.4.3"]

to the boot dependencies helps. Adding pomegranate makes somewhat sense, then digest_init came up, so I added this one, even thought I didn't find the dependency to digest somewhere.

the #10 problem is still there, but Micha Niskin wrote this fix is supposed to be in dev branch, so maybe shouldn't have been fixed yet in master anyway.

**Comment by mynomoto** [comment]
You need to change the version of `boot.core` in `build.boot`. On line 3 this:

```
#tailrecursion.boot.core/version "2.2.1"
```

Needs to be this:

```
#tailrecursion.boot.core/version "2.3.1"
```

@micha Sorry for bothering you at IRC, boot.core version was the problem.

**Comment by mynomoto** [comment]
@micha I've been thinking about this and probably boot should at least warn you that you can't use boot.core 2.2.1 or below instead of failing like that. Also I think you were right about bump the version to 2.0.0 because of this compatibility issue with boot.core.

**Comment by bergm** [comment]
@mynomoto Thanks for the hint. I wouldn't have thought into this direction. :-)
