### ISSUE TITLE
Mess with ANSI-enhanced console output on Windows

### ISSUE THREAD

**Issue by vmarcinko** [tailrecursion/boot#14]
ANSI-colored output makes certain text unreadable, or even disrupts completely proper printout on Windows console - eg. when there is period since last action printed each second - ANSI codes disrupts printing over same piece of text ,and instead fills complete console with formatted period text over time.

Here's an example of output:

```
Compiling Hoplon pages...
Ľ src\index.cljs.hl
Compiling ClojureScript...
←[34m? Elapsed time: 13,318 sec Ť←[33m 00:00:00 00:00:13 00:00:13 00:00:14 00:00:14 00:00:1 00:00:16 00:00:16 00:00:16 00:00:17 00:00:17 00:00:17 00:00:17 00:00:18 00:00:18 00:00:18 0 00:00:20 00:00:20 00:00:20 00:00:21 00:00:21 00:00:21 00:00:21 00:00:22 00:00:22 00:00:22 0
```

So the solution would be to avoid using ANSI codes altogether, or to differentiate output based on OS..

**Comment by bergm** [comment]
Isn't fixing the problem, but using cygwin helps in this case. :-)

**Comment by vmarcinko** [comment]
Actually, I have cygwin, and it doesn't give correct output also (i know there are also some ANSI enhancers for windows terminals, but didn't try them), all kind of mess for some reason, but even if it did it correctly, its not solution for general windows community which just uses plain (admittedly, quite awful) terminal. :)

**Comment by bergm** [comment]
You're right not everything works correctly, but at least the cursor stays at the same position, so the elapsed time doesn't fill the console screen.

**Comment by csells** [comment]
I just installed boot with the Windows download a few hours ago and I'm getting the console filling behavior as well. I'm not using Cygwin.

**Comment by micha** [comment]
I'll add an option to the watch task to disable the console output. That
should help as a workaround, at least.

## 

Micha Niskin

**Comment by micha** [comment]
This is implemented in boot2 [boot-clj/boot](http://github.com/boot-clj/boot).
