### ISSUE TITLE
boot.core/version "2.3.1" causes error if boot.notify is missing in dependencies

### ISSUE THREAD

**Issue by bergm** [tailrecursion/boot#15]
Just stumbled over another problem:

I suddenly got 

$ boot dev
org/codehaus/plexus/util/xml/pull/XmlSerializer
? Caused by: org.codehaus.plexus.util.xml.pull.XmlSerializer

at the cygwin prompt, upon starting 'boot dev' on my project. Hoplife, counter et.al. worked. Finally I found that I had to add 

[tailrecursion/boot.notify "2.0.0-snapshot"] 

to my dependencies (which wasn't there yet as my initial template was from times before this has been added to every example).

**Comment by micha** [comment]
I think this is fixed. Please feel free to reopen if it's not.
