### ISSUE TITLE
Proxy issues?

### ISSUE THREAD

**Issue by rrichardson** [tailrecursion/boot#2]
When I try to run the hoplon examples with boot,  it just sits there for a very long time, which, after the subsequent stack trace, looks to be 4 retry timeouts.  

I am behind a corporate proxy, I have environment settings for proxies that Leiningen seems to understand but boot does not.   

It would be nice if:  
1. boot told me that it was attempting to fetch dependencies. 
2. told me the first time it timed out reaching the interwebs. 
3. understood the http(s)_proxy env var. 

On a side note, I'm sure you have some very good reasons for why boot isn't just a plugin for leiningen.. care to share what those are?

**Comment by alandipert** [comment]
Hi, thanks for stopping by.  I added `http_proxy` env var support, but haven't tested - would you mind pulling, rebuilding, and confirming that it's fixed?

Re: moving from Leiningen, I attempted to [summarize on Reddit](http://www.reddit.com/r/Clojure/comments/1t6wgs/hoplon_a_simpler_way_to_program_the_web/ce5zntf).

**Comment by rrichardson** [comment]
I am back at home so I stood up a squid proxy and pointed http(s)_proxy to it, then watched packets going over it with tcpdump.  I am fairly confident that the fix would work well in an oppressive corporate environment.
