### ISSUE TITLE
watch slow for add-sync! assets

### ISSUE THREAD

**Issue by Cottin** [tailrecursion/boot#22]
Using a similar build.boot as in demos/hoplife, I have the browser auto-refreshing when I change *.cljs.hl files.

```
(set-env!
 :dependencies (read-string (slurp "deps.edn"))
 :src-paths    #{"src"}
 :out-path     "resources/public")

(add-sync! (get-env :out-path) #{"resources/assets"})

(deftask development
  "Build for development"
  [& args]
  (comp
   (watch)
   #_(hear)
   (hoplon {:prerender false})
   (dev-server)))
```

When I make changes to resources/assets/main.css it takes between 0.5 and 3 seconds for the copying of files to the out-path and refreshing of the browser to happen. This is just too long comparing with a normal set up with for instance gulp. Is this the expected time to wait? Any way to make it faster?

**EDIT:**
I've investigated it further and the problem seems to be with chrome. Firefox refreshes the style instantaneously but Chrome does not refresh it at all. Chrome only refresh the style on mouse enter. That is, if I hover my mouse over the page in the chrome window, then (and only then) it refreshes... Known issue? (Tested with Chrome 35 and 37)

**Comment by micha** [comment]
This is probably being caused by a WebKit bug. [You can try this CSS workaround](https://github.com/adzerk/boot-cljs-example/blob/master/html/css/main.css#L1-L4), it will almost certainly fix the problem. If not please feel free to reopen the ticket :)
