### ISSUE TITLE
Readme "Hello World" example hangs

### ISSUE THREAD

**Issue by hugoduncan** [tailrecursion/boot#33]
Following the instructions in the readme, running `build.boot` for the "Hello World" example hangs.  The first time through it downloads `tailrecursion.boot.core/version "2.5.0"` and then hangs.

This is on OS X, java 1.7.0 55.

**Comment by micha** [comment]
Closing this issue in preparation for moving hoplon to [boot-clj/boot](http://github.com/boot-clj/boot).
