### ISSUE TITLE
boot pollutes non-project directories with .boot dirs

### ISSUE THREAD

**Issue by jumblerg** [tailrecursion/boot#35]
this is obviously a bug because these annoy me when i look at them.

discussed with micha. smoking weed might be a fix of sorts, but not a viable solution.  subsequently suggested approach involves having "-main use a java tempfile instead of a boot tempfile so that boot dirs won't be created unless a task makes tempfile".

**Comment by micha** [comment]
Fixed in bfb6758ef0d51c5bb59599eb3bbc7b0bddab182b
