### ISSUE TITLE
Exception in thread "main" clojure.lang.ArityException

### ISSUE THREAD

**Issue by kxcrl** [tailrecursion/boot#4]
Hi,

I'm really looking forward to playing with Hoplon, but I'm having some trouble getting boot up and running. Trying to run 'boot' with the edn file in fixtures throws the following (from boot/test/fixtures):

Exception in thread "main" clojure.lang.ArityException: Wrong number of args (0) passed to: loader$-main

Trying to run 'boot' from a newly generated hoplon app folder throws the same error. 
Trying to run 'boot help' to make sure I'm not missing any flags throws:

Exception in thread "main" clojure.lang.ArityException: Wrong number of args (1) passed to: loader$-main

And finally, trying to run 'boot watch hoplon' from a newly generated hoplon app folder throws:
Error: Could not find artifact tailrecursion:boot.core:jar:watch in http://repo1.maven.org/maven2/ (http://repo1.maven.org/maven2/)
Error: Could not find artifact tailrecursion:boot.core:jar:watch in http://clojars.org/repo/ (http://clojars.org/repo/)

Is this just me? If so, any advice for what I'm missing here?

**Comment by micha** [comment]
Sorry, we were in the middle of updating some things, but we didn't
coordinate the changes correctly. Please re-pull boot and rerun `make boot`
and you should be okay. Let me know if it's still broken, if you can.
Thanks!

## 

Micha Niskin

**Comment by kxcrl** [comment]
Ah, no problem. Glad I asked.

Ran out of memory during the ClojureScript compile on 'boot watch hoplon', so I ended up running it again with JVM-OPTS="-Xmx2g", which worked great. Running 'boot' in boot/test/fixtures now throws a huge wall of text error, but that's not going to hold me back, of course.

Thanks!

**Comment by micha** [comment]
Ah, right. The stuff in boot/test is currently just stuff I am using locally; it's not part of a real test harness yet.

**Comment by kxcrl** [comment]
Makes sense. I'll stop messing with it, then. = )
