### ISSUE TITLE
Runtime Exception

### ISSUE THREAD

**Issue by jeemar** [tailrecursion/boot#41]
Trying to do `boot development` for hoplon-demos and ran into this. I tried infinite-scroll and plotSVG.
I'm not sure why. 

```
java.lang.RuntimeException: No reader function for tag tailrecursion.boot.core/version
                          ...                
     clojure.core/read-string  core.clj: 3497
    boot.util/read-string-all  util.clj:  134
              boot.main/-main  main.clj:  104
                          ...                
             boot.App.runBoot  App.java:  217
                boot.App.main  App.java:  309
```

I'm running Mac OSX Yosemite with:

```
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

**Comment by alandipert** [comment]
Hello - it looks like you're running Boot 2 ([from boot-clj/boot](https://github.com/boot-clj/boot)) when you still need Boot 1 ([from tailrecursion/boot, this repo](https://github.com/tailrecursion/boot/)) to run Hoplon.

I have them both installed, but I renamed the executables `boot2` and `boot1`.  Unfortunately we haven't ported Hoplon to `boot2` yet, and `boot2` is not backward compatible, so at least for a little while it's a good idea to have them both installed.

The particular reason for this error is that `boot2` doesn't recognize the `#tailrecursion.boot.core/version` data literal, which is characteristic of `boot1` `build.boot` files.

**Comment by jeemar** [comment]
That makes sense! Thanks Alan!
