### ISSUE TITLE
AssertionError: Configuration must be a map 

### ISSUE THREAD

**Issue by stevekrouse** [tailrecursion/boot#5]
Trying to install boot from source, I the following error running `./boot` after install with `make boot`.

```
Exception in thread "main" java.lang.AssertionError: Assert failed: boot.edn (Configuration must be a map) 
(map? p1__403#)
    at tailrecursion.boot.loader$read_config$asrt_m__405.invoke(loader.clj:43)
    at tailrecursion.boot.loader$read_config.invoke(loader.clj:44)
    at tailrecursion.boot.loader$_main.doInvoke(loader.clj:100)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.AFn.applyToHelper(AFn.java:159)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at tailrecursion.boot.loader.main(Unknown Source)`
```

**Comment by micha** [comment]
Do you have a `boot.edn` file in the current directory?

**Comment by stevekrouse** [comment]
I have `boot/test/fixtures/boot.edn`. Where should it be?

**Comment by micha** [comment]
Are you trying to build a Hoplon application? If so you can do `lein new hoplon my-project` to create a new project directory with a `boot.edn` file included with the latest versions of everything you need. The `test/fixtures` file is just something used during testing and not something you'd want to use.

**Comment by stevekrouse** [comment]
I'm trying to install boot from source and there is no `.edn` file in the main directory.

**Comment by micha** [comment]
It looks like you've achieved that already, if `make boot` succeeded and you moved `./boot` to somewhere on your path then you've successfully built it from source and installed it.

**Comment by micha** [comment]
The `boot.edn` file is what you need to use boot to build a project.

**Comment by stevekrouse** [comment]
Ha! Now I get it! I have to run boot in a directory with a `.edn` file. 

But in my defense, the error supplied for running boot in a directory without a `.edn` file is pretty cryptic. Something like "No .edn file found" would work. I thought something went wrong in the compile process or something having to due with maps (like it says in the error).

**Comment by micha** [comment]
You're right, the "must be a map" business is confusing :)

**Comment by stevekrouse** [comment]
Thanks so much!

**Comment by micha** [comment]
You're welcome, good luck!
