### ISSUE TITLE
Integrate into Leiningen

### ISSUE THREAD

**Issue by darth10** [tailrecursion/boot#7]
Is it possible to integrate boot as a whole into Lein?  :smile: 
Maybe it can be a implemented as Lein plugin too.

I'm just asking this as the Clojure community already has a great build and dependency  tool - Leiningen. Boot does add interesting functionality, such as `:require-tasks` and use of EDN format. Perhaps it can be made into a plugin, so that users don't have to use two build tools when working with projects that use boot.

**Comment by micha** [comment]
Pull requests always welcome :). If it can be implemented as a Lein plugin or whatever without losing functionality then I'm game. I don't really see how that can be done, though.

**Comment by darth10** [comment]
Alrighty then.
