### ISSUE TITLE
boot watch hoplon java.lang.RuntimeException

### ISSUE THREAD

**Issue by tjiahen** [tailrecursion/boot#9]
# boot watch hoplon

java.lang.RuntimeException: Invalid token: Error:
at clojure.lang.Util.runtimeException (Util.java:219)
    clojure.lang.LispReader.interpretToken (LispReader.java:326)
    clojure.lang.LispReader.read (LispReader.java:211)
    clojure.lang.LispReader.readDelimitedList (LispReader.java:1157)
    clojure.lang.LispReader$ListReader.invoke (LispReader.java:982)
    clojure.lang.LispReader.read (LispReader.java:185)
    clojure.lang.RT.readString (RT.java:1738)
    clojure.core$read_string.invoke (core.clj:3427)
    tailrecursion.boot.loader$_main.doInvoke (loader.clj:169)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    tailrecursion.boot.loader.main (:-1)

> > build.boot
> > Error: Could not find artifact tailrecursion:ancient-clj:jar:0.1.7 in http://repo1.maven.org/maven2/ (http://repo1.maven.org/maven2/)
> > Retrieving org/apache/httpcomponents/httpclient/4.3.1/httpclient-4.3.1.jar from http://repo1.maven.org/maven2/
> > Error: Could not find artifact clj-http:clj-http:jar:0.7.8 in http://repo1.maven.org/maven2/ (http://repo1.maven.org/maven2/)
> > Retrieving org/apache/httpcomponents/httpmime/4.3.1/httpmime-4.3.1.jar from http://repo1.maven.org/maven2/
> > Retrieving org/apache/httpcomponents/httpcore/4.3/httpcore-4.3.jar from http://repo1.maven.org/maven2/
> > Retrieving commons-io/commons-io/2.4/commons-io-2.4.jar from http://repo1.maven.org/maven2/
> > Error: Could not find artifact slingshot:slingshot:jar:0.10.3 in http://repo1.maven.org/maven2/ (http://repo1.maven.org/maven2/)
> > Error: Could not find artifact cheshire:cheshire:jar:5.2.0 in http://repo1.maven.org/maven2/ (http://repo1.maven.org/maven2/)
> > Retrieving com/fasterxml/jackson/core/jackson-core/2.2.1/jackson-core-2.2.1.jar from http://repo1.maven.org/maven2/
> > Retrieving com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.2.1/jackson-dataformat-smile-2.2.1.jar from http://repo1.maven.org/maven2/
> > Error: Could not find artifact tigris:tigris:jar:0.1.1 in http://repo1.maven.org/maven2/ (http://repo1.maven.org/maven2/)
> > Retrieving org/jsoup/jsoup/1.7.1/jsoup-1.7.1.jar from http://repo1.maven.org/maven2/
> > Retrieving org/clojure/tools.reader/0.8.1/tools.reader-0.8.1.jar from http://repo1.maven.org/maven2/
> > Retrieving commons-codec/commons-codec/1.8/commons-codec-1.8.jar from http://repo1.maven.org/maven2/
> > Error: Could not find artifact crouton:crouton:jar:0.1.1 in http://repo1.maven.org/maven2/ (http://repo1.maven.org/maven2/)
> > Retrieving commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar from http://repo1.maven.org/maven2/
> > Retrieving tailrecursion/ancient-clj/0.1.7/ancient-clj-0.1.7.jar from http://clojars.org/repo/
> > Retrieving clj-http/clj-http/0.7.8/clj-http-0.7.8.jar from http://clojars.org/repo/
> > Retrieving cheshire/cheshire/5.2.0/cheshire-5.2.0.jar from http://clojars.org/repo/
> > Retrieving slingshot/slingshot/0.10.3/slingshot-0.10.3.jar from http://clojars.org/repo/
> > Retrieving tigris/tigris/0.1.1/tigris-0.1.1.jar from http://clojars.org/repo/
> > Retrieving crouton/crouton/0.1.1/crouton-0.1.1.jar from http://clojars.org/repo/
> > # !/usr/bin/env boot
# tailrecursion.boot.core/version "2.0.0"

(set-env!
  :project
  'my-project
  :version
  "0.1.0-SNAPSHOT"
  :dependencies
  [['tailrecursion/boot.core "2.0.0"]
   ['tailrecursion/boot.task "2.0.0"]
   ['tailrecursion/hoplon "5.0.0"]
   ['org.clojure/clojurescript "0.0-2156"]]
  :src-paths
  #{"src"}
  :out-path
  "resources/public")

(require
  ['tailrecursion.hoplon.boot :refer :all]
  ['tailrecursion.boot.task :refer :all])

> > boot.edn

{:project       my-project
 :version       "0.1.0-SNAPSHOT"
 :dependencies  [[tailrecursion/boot.core   "1.2.3"]
                 [tailrecursion/boot.task   "1.0.2"]
                 [tailrecursion/hoplon      "4.0.12"]
                 [org.clojure/clojurescript "0.0-2156"]]
 :require-tasks #{[tailrecursion.boot.task    :refer :all]
                  [tailrecursion.hoplon.boot  :refer :all]}
 :public        "resources/public"
 :src-paths     #{"src"}}

**Comment by micha** [comment]
This was caused by #8. The fix is to rebuild boot, version 1.0.2 or later and then recreate your `build.boot` file:

```
$ boot :fixup > build.boot
```

Sorry about that!
